# Generated by Django 5.2.5 on 2025-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='marketplaces/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
