# Generated by Django 5.2.5 on 2025-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='catalog_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
