# Generated by Django 5.2.5 on 2025-08-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_marketplace_catalog_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='catalog_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
