# Generated by Django 5.2.5 on 2025-08-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_marketplace_catalog_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='catalog_link',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='link',
        ),
    ]
