# Generated by Django 5.2.5 on 2025-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='marketplace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='home.marketplace'),
            preserve_default=False,
        ),
    ]
