# Generated by Django 5.2.5 on 2025-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shop_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/i.webp', null=True, upload_to='products/'),
        ),
    ]
